### ISSUE TITLE
2.2.0: "Disable background images" stopped working

### ISSUE THREAD

**Issue by Gittyperson** [Gnat008/nosquint#8] opened 2018-06-11 22:05 UTC
Thank you for this update. I think something in this version is interfering with this feature. Check these two websites:

https://www.athenstransport.com/
http://www.cinemagazine.gr/

In 2.1.10 Disable background images works. In 2.2.0 it doesn't.

On the first website only, if you toggle the option the background will disappear, but it will re-appear on the next refresh. On the second website, toggling does nothing.

Pale Moon 28.0.0a4, Win 10 Pro x64

**Comment by Gnat008** [comment] 2018-06-11 23:58
The same appears to be true for all of the colorizing options. I'll dig around and try to find what change caused this.

**Comment by Gnat008** [comment] 2018-06-12 00:42
It looks like the styling is being applied *before* the rest of the website's styling, and thus is being overridden.

**Comment by Gnat008** [comment] 2018-06-14 21:19
Okay, I figured out that all this was caused by moving to the new global TabsProgressListener. :/

I reverted that change, and did some minor cleanup. Will publish the update on PM shortly. Sorry about that.

**Closed** 2018-06-14 21:28 UTC
Labels: bug, regression
